float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorIVFFlat
    disabled: false
    docker_tag: ann-benchmarks-pgvector-ivfflat
    module: ann_benchmarks.algorithms.pgvector-ivfflat
    name: pgvector-ivfflat
    run_groups:
      pgvector-ivfflat:
        args: [[100, 200, 400, 1000, 2000, 4000]]
        query_args: [[1, 2, 4, 10, 20, 40, 100]]